apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- toYaml .Values.selectorLabels | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- toYaml .Values.podLabels | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: SMB_USERNAME
            value: {{ .Values.smbUserName | default "" }}
          - name: SMB_PASSWORD
            value: {{ .Values.smbPassword | default "" }}
            {{- if .Values.smbInputPath }}
          - name: SMB_INPUTPATH
            value: {{ .Values.smbInputPath }}
            {{- end }}
            {{- if .Values.smbOutputPath }}
          - name: SMB_OUTPUTPATH
            value: {{ .Values.smbOutputPath }}
            {{- end }}
          - name: SLEEPTIME
            value: {{ .Values.smbSleepTime | default 5 | quote }}
          volumeMounts:
            {{- with .Values.folderMounts }}
            {{- if .input.enabled }}
          - mountPath: /input
            name: input-folder
            {{- end }}
            {{- if .output.enabled }}
          - mountPath: /output
            name: output-folder
            {{- end }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      {{- with .Values.folderMounts }}
      {{- if .input.enabled }}
      - name: input-folder
        {{- .input.volume | toYaml | nindent 8 }}
      {{- end }}
      {{- if .output.enabled }}
      - name: output-folder
        {{- .output.volume | toYaml | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
