name: Package and push helm-charts

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

  workflow_dispatch:

jobs:
  package-and-push:
    runs-on: ubuntu-latest
    env:
      HELM_REPO: energinet-singularity/helm-registry
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: local

      - name: Checkout helm-registry
        uses: actions/checkout@v2
        with:
          repository: ${{ env.HELM_REPO }}
          path: helm
          branch: main

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Pack chart, generate index and update repo
        env:
          GIT_USERNAME: singu-bot
        run: |
          CHART_NAME=$(grep "name: " local/chart/Chart.yaml | cut -f2 -d' ')
          CHART_VERSION=$(grep "version: " local/chart/Chart.yaml | cut -f2 -d' ')
          cd helm
          helm package "../local/chart/"
          echo "1"
          helm repo index .
          echo "2"
          git config user.name "${{ env.GIT_USERNAME }}"
          git config user.email "${{ secrets.SINGU_BOT_EMAIL }}"
          echo "3"
          #git remote add origin https://{username}:{password}@github.com/{username}/project.git
          git add .
          echo "4"
          git commit -m "Autopack/$CHART_NAME/v:$CHART_VERSION"
          echo "5"
          #git config -l | grep 'http\..*\.extraheader' | cut -d= -f1 | xargs -L1 git config --unset-all
          #git push "https://${{ secrets.SINGU_BOT_TOKEN }}@github.com/${{ env.HELM_REPO }}" main:main
          git push https://${{ secrets.SINGU_BOT_TOKEN }}@github.com/${{ env.HELM_REPO }}.git main
          echo "6"
