name: Package and push helm-charts

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

  workflow_dispatch:

jobs:
  package-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: local

      - name: Checkout helm-registry
        uses: actions/checkout@v2
        with:
          repository: energinet-singularity/helm-registry
          path: helm
          branch: main

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Package chart
        id: meta
        run: |
          CHART_NAME=$(grep "name: " local/chart/Chart.yaml | cut -f2 -d' ')
          echo "::set-output name=NAME::$CHART_NAME"
          CHART_VERSION=$(grep "version: " local/chart/Chart.yaml | cut -f2 -d' ')
          echo "::set-output name=VERSION::$CHART_VERSION"
          cd helm
          helm package "../local/chart/"

      - name: Generate new index and update repository
        run: |
          cd helm
          helm repo index .
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit -m "Autopack/${{ steps.meta.NAME }}/v:${{ steps.meta.VERSION }}"
          #git push
