name: Package and push helm-charts

on:
  push:
    branches:
      - main
    paths:
      - 'chart/**'

  workflow_dispatch:

jobs:
  package-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: local

      - name: Checkout helm-registry
        uses: actions/checkout@v2
        with:
          repository: energinet-singularity/helm-registry
          path: helm
          branch: main

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Package chart
        run: |
          CHART_NAME=$(grep "name: " local/chart/Chart.yaml | cut -f2 -d' ')

      - name: Generate new index
        run: |
          cd helm
          helm repo index .

      - name: Update repository
        run: |
          echo "Starting in $PWD"
          #cd helm
          #git commit -m "Autopack/${{ steps.id.NAME }}/v:${{ steps.id.VERSION }}"
          #git push
