name: Verify version has changed

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  get-version-numbers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Get pull version numbers
        run: | 
          HELM_VERSION=$(grep "version: " chart/Chart.yaml | cut -f2 -d' ')
          echo "Helm Chart version is: '$HELM_VERSION'"
          # To skip version checking of version in values file, comment out the rest of this step
          VALUES_VERSION=$(grep "tag: " chart/values.yaml | cut -f2 -d'"')
          echo "Helm values version is: '$VALUES_VERSION'"
          if [ "$HELM_VERSION" != "$VALUES_VERSION" ]; then
            echo "Chart and values file versions do not match."
            exit 1
          fi

      - name: Get latest package version number
        run: |
          curl -u "${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}" https://ghcr.io/v2/energinet-singularity/file-mover/tags/list
